run:
  tests: false

issues:
  fix: false

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    # Deprecated.
    - varcheck
    - maligned
    - scopelint
    - structcheck
    - nosnakecase
    - interfacer
    - ifshort
    - golint
    - deadcode
    - exhaustivestruct

    # Handle formatting separately.
    - gci
    - gofmt
    - gofumpt
    - goimports

    # Not useful here
    - depguard
    - godox
    - varnamelen
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 12

  exhaustive:
    default-signifies-exhaustive: true

  exhaustruct:
    exclude:
      - "^github.com/urfave/cli/v2.App$"
      - "^github.com/urfave/cli/v2.BoolFlag$"
      - "^github.com/urfave/cli/v2.Command$"
      - "^github.com/urfave/cli/v2.StringFlag$"
      - "^github.com/urfave/cli/v2.StringSliceFlag$"
      - "^github.com/coffeebeats/gdpack/pkg/manifest.Asset$"
      - "^github.com/coffeebeats/gdpack/pkg/manifest.Git$"
      - "^github.com/coffeebeats/gdpack/pkg/manifest.Local$"
      - "^github.com/coffeebeats/gdpack/pkg/manifest.Manifest$"
      - "^github.com/coffeebeats/gdpack/pkg/manifest.Spec$"

  gomnd:
    ignored-numbers:
      - "0700"
      - "0600"

  varnamelen:
    ignore-decls:
      - c *cli.Context
