[package]
name = "gdpack"
version = "0.0.8"
description = "A small, single-purpose CLI application for managing Godot addons."
edition = "2021"
rust-version = "1.74.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.10", features = ["cargo", "derive"] }
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.8.8"
toml_edit = { version = "0.21.0", features = ["serde"] }
url = { version = "2.5.0", features = ["serde"] }
