[package]
name = "gdpack"
version = "0.0.12"
description = "A small, single-purpose CLI application for managing Godot addons."
edition = "2021"
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.16", features = ["cargo", "derive"] }
git2 = "0.18.1"
reqwest = { version = "0.11.23", features = ["blocking"] }
rust-ini = { version = "0.20.0", features = ["inline-comment"] }
semver = "1.0.21"
serde = { version = "1.0.195", features = ["derive"] }
tempfile = "3.9.0"
thiserror = "1.0.56"
toml = "0.8.8"
toml_edit = { version = "0.21.0", features = ["serde"] }
typed-builder = "0.18.0"
url = { version = "2.5.0", features = ["serde"] }
walkdir = "2.4.0"
zip = "0.6.6"

# FIXME(https://github.com/actions-rs/cargo/issues/227): This works around a
# cross-compilation issue seen in GitHub actions runs where `openssl-sys` cannot
# be compiled when using `cross`. This approach does affect _all_ usage of
# `openssl-sys`, but consistency is preferred at the moment over trying to set
# this per target.
[dependencies.'openssl-sys']
features = ["vendored"]
