# Target 'GLIBC 2.17' using 'zig cc' as a cross-compiler
[target.x86_64-unknown-linux-gnu]
zig = "2.17"

# Pre-install a compatible version of `openssl` (see https://github.com/cross-rs/cross/wiki/Recipes#openssl).
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH",
]
