name: "🤖 Set up: 'gdpack'"
description: "Install the specified version of 'gdpack' and, optionally, install project dependencies."

inputs:
  version:
    description: "The version of 'gdpack' to install."
    required: false
    default: "latest"
  install-dir:
    description: "The 'gdpack' installation directory."
    required: false
    default: "$HOME/.gdpack"
  modify-path:
    description: "Whether to add the 'gdpack' command to 'PATH'."
    required: false
    default: true
  project-dir:
    description: "A path to a Godot project containing a manifest file."
    required: false
    default: "."
  skip-install:
    description: "Whether to skip installing project dependencies."
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Export the 'GDPACK_HOME' environment variable
      shell: bash
      run: echo "GDPACK_HOME=${{ inputs.install-dir }}" >> $GITHUB_ENV

    - name: Cache the 'gdpack' home directory
      id: cache-gdpack
      uses: actions/cache@v4
      with:
        path: ${{ env.GDPACK_HOME }}
        key: gdpack-${{ runner.os }}-${{ inputs.version }}-${{ inputs.install-dir }}-${{ hashFiles(format('{0}/**/*', inputs.project-dir)) }}
        restore-keys: |
          gdpack-${{ runner.os }}-${{ inputs.version }}-${{ inputs.install-dir }}-
    
    # See https://github.com/coffeebeats/gdpack/blob/main/docs/installation.md#linuxmacos.
    - name: Install 'gdpack' (latest)
      if: steps.cache-gdpack.outputs.cache-hit != 'true' && inputs.version == 'latest'
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/coffeebeats/gdpack/main/scripts/install.sh | sh -s -- --no-modify-path

    # See https://github.com/coffeebeats/gdpack/blob/main/docs/installation.md#manual-download.
    - name: Install 'gdpack'
      if: steps.cache-gdpack.outputs.cache-hit != 'true' && inputs.version != 'latest'
      shell: bash
      run: |
        ARCH=x86_64
        OS="$(echo "$(uname -s)" | tr '[:upper:]' '[:lower:]')"
        VERSION="$(echo "${{ inputs.version }}" | sed 's/^v//')"

        curl -LO "https://github.com/coffeebeats/gdpack/releases/download/v${VERSION#v}/gdpack-$VERSION-$OS-$ARCH.tar.gz"

        mkdir -p $GDPACK_HOME/bin && \
        tar -C $GDPACK_HOME/bin -xf gdpack-$VERSION-$OS-$ARCH.tar.gz
    
    - name: Update the 'PATH' environment variable
      if: inputs.modify-path == 'true'
      shell: bash
      run: echo "$GDPACK_HOME/bin" >> $GITHUB_PATH

    - name: Validate that the 'gdpack' executable was installed
      shell: bash
      run: |
        if ! command -v gdpack >/dev/null; then
          echo "Failed to install 'gdpack'!"
          exit 1
        fi
    
    - name: Install project dependencies
      if: inputs.skip-install == 'false'
      shell: bash
      run: gdpack install --project ${{ inputs.project-dir }} -t ci
