name: "🚀 Release: 'gdpack'"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    outputs:
      release-created: ${{ steps.release.outputs.releases_created }}
      release-tag: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # NOTE: A PAT is used so that workflows can run on the new, automatically
          # created pull requests. This circumvents GitHub's recursive workflow
          # protections, which block automated pull requests from triggering workflows
          # under the same default GitHub Actions token.
          token: ${{ secrets.RELEASE_PLEASE }}

          # NOTE: To handle releases on specific branches (e.g. a '1.X' release branch),
          # simply change the "branches" filter in the workflow's on-"push" trigger.
          default-branch: ${{ github.ref_name }}
          release-type: "rust"

          package-name: "gdpack"

          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: true

          pull-request-title-pattern: "chore: release v${version}"
          changelog-notes-type: "github"

          extra-files: |
            docs/installation.md
            scripts/install.ps1
            scripts/install.sh

  build:
    needs: ["release-please"]
    if: needs.release-please.outputs.release-created

    runs-on: ${{ matrix.os }}
    timeout-minutes: 8

    strategy:
      fail-fast: false # do not exit early
      matrix:
        include:
          # Apple
          - target: aarch64-apple-darwin
            label: macos-arm64
            os: macos-latest
          - target: x86_64-apple-darwin
            label: macos-x86_64
            os: macos-latest

          # Linux
          - target: x86_64-unknown-linux-gnu
            label: linux-x86_64
            os: ubuntu-latest
            use_cross: true

          # Windows
          - target: x86_64-pc-windows-msvc
            label: windows-x86_64
            os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/setup-rust"
        id: setup-rust
        with:
          profile: minimal
          version-file: Cargo.toml
          targets: ${{ matrix.target }}

      # Set minimum supported version to '11.1', which guarantees support for
      # M1 macs (see https://developer.apple.com/support/xcode).
      - name: Set OSX environment variables
        if: endsWith(matrix.target, 'apple-darwin')
        run: |
          echo "SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=11.1" >> $GITHUB_ENV

      - uses: "./.github/actions/cargo-build"
        with:
          profile: release
          platform: ${{ matrix.target }}
          targets: bins
          use_cross: ${{ matrix.use_cross }}

      - name: Create asset
        id: create-archive
        run: |
          ARCHIVE_NAME="gdpack-${{ needs.release-please.outputs.release-tag }}-${{ matrix.label }}"

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ARCHIVE_NAME="$ARCHIVE_NAME.zip"

            zip \
              $ARCHIVE_NAME \
              "target/${{ matrix.target }}/release/gdpack.exe"
          else
            ARCHIVE_NAME="$ARCHIVE_NAME.tar.gz"

            tar \
              -C "target/${{ matrix.target }}/release" \
              -czf $ARCHIVE_NAME \
              "gdpack"
          fi

          echo "name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.target }}
          path: ${{ steps.create-archive.outputs.name }}
          if-no-files-found: error

  publish:
    needs: ["release-please", "build"]
    if: needs.release-please.outputs.release-created

    runs-on: ubuntu-latest
    timeout-minutes: 4

    env:
      FILENAME_CHECKSUMS: "checksums.txt"

    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          path: ${{ runner.temp }}/assets

      - name: Generate checksums file
        working-directory: ${{ runner.temp }}/assets
        run: |
          checksum() {
            if [[ "${{ runner.os }}" == "macOS" ]]; then
              shasum -a 256 "$@"
            else
              sha256sum "$@"
            fi
          }

          for artifact in $(ls); do
            echo "$(cd $artifact && checksum $(ls))" >> ${{ env.FILENAME_CHECKSUMS }}
          done

      - name: Attach assets to release
        working-directory: ${{ runner.temp }}/assets
        env:
          # This is required to use the 'gh' CLI in actions.
          GH_TOKEN: ${{ github.token }}
        run: |
          ASSETS=(*/gdpack-${{ needs.release-please.outputs.release-tag }}* checksums.txt)
          for asset in "${ASSETS[@]}"; do
            gh release upload \
              --clobber \
              ${{ needs.release-please.outputs.release-tag }} \
              $asset
          done
